services:
  myapp:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ~/.aws:/UI_user/.aws:ro # AWS credentials (read only)
      - ~/.ssh:/UI_user/.ssh:ro  # Mount SSH keys (read only)
